### ISSUE TITLE
be able to autofill templates with users data or manually change them

### ISSUE THREAD

**Issue by Jakeclearwater** [BIT-Studio-OP/CraftMyPortfolio#56]
when loading a template, it should auto fill in required areas with users data filled out in the form but they should have access to manually edit this on the template

**Comment by Dani-op** [comment]
This issue now allows the user to get the information from Firebase when they have been navigated to /details form, and they can also update the data from the details.
![chrome_4X821fLV9P](https://github.com/BIT-Studio-OP/CraftMyPortfolio/assets/81060521/d19f3069-20f5-48aa-8c6b-91f8e54e17df)

So I will be increasing the scope of this issue to combine multiple tasks that are critically related to each other...
