### ISSUE TITLE
testing for login and register

### ISSUE THREAD

**Issue by Jakeclearwater** [BIT-Studio-OP/CraftMyPortfolio#59]
testing with jest for login and register forms, can get away without using firebase for this but will need to be done in the future

**Comment by kierenblack** [comment]
## Test results 12/10/2023

After registering, logging in and browsing the site, the experience is easy and understandable.

While navigating the site there was an issue found with the logout. Once you logout, you are not redirected to a page stating you have logged out. The page is just blank with no knowledge of what is happening.
