### ISSUE TITLE
feat: Templates to Editing

### ISSUE THREAD

**Issue by Dani-op** [BIT-Studio-OP/CraftMyPortfolio#67]
I have laid out the idea in the attachment below that the templates nav link currently leads directly to template editing, but we would like to move things along by having the templates page show you a variety of templates before taking you select a template to edit.
Please feel free to ask questions about it Thanks!.
![firefox_QjfFYoOAKk](https://github.com/BIT-Studio-OP/CraftMyPortfolio/assets/81060521/aa5fb2ee-c82e-47ce-87f9-77b72c20abf4)

**Comment by Jakeclearwater** [comment]
i can help where needed @Perkitw2
